[parity]
chain = "/iexec-poco/testchains/parity/20sec/chain.json"

[account]
unlock = ["0xc08c3def622af1476f2db0e3cc8ccaead07be3bb"]
password = ["/iexec-poco/testchains/parity/20sec/password"]

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "pubsub", "parity_pubsub", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[mining]
reseal_on_txs = "none"
engine_signer = "0xc08c3def622af1476f2db0e3cc8ccaead07be3bb"
force_sealing = true

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "pubsub", "parity_pubsub", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]
hosts = ["all"]
