name: Deploy PoCo Contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        type: choice
        options:
          - hardhat
          - arbitrumSepolia
          - arbitrum
          - bellecour
        default: 'hardhat'

jobs:
  # Build and test before deploying.
  build-and-test:
    uses: ./.github/workflows/main.yml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: ${{ inputs.network }} # Use the selected environment
    permissions:
      contents: write # Required to commit artifacts.
      pull-requests: write # Required to create pull requests.
    env:
      # For commit action
      COMMIT_MESSAGE: 'chore: Save artifacts - ${{ inputs.network }} (runId:${{ github.run_id }})'
      GHA_BOT_NAME: 'GitHub Actions Bot'
      GHA_BOT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Cache dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # TODO activate later.
      # - name: Run fork tests
      #   run: |
      #     if [ "${{ inputs.network }}" == "arbitrumSepolia" ]; then
      #       npm run test:arbitrumSepolia
      #     fi

      - name: Deploy contracts
        env:
          # Note: it is required to define both private key env variables when calling Hardhat.
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          ARBISCAN_API_KEY: ${{ secrets.ARBISCAN_API_KEY }}
          # TODO: Use Etherscan V2 API
          # EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}
          # IS_VERIFICATION_API_V2: ${{ vars.IS_VERIFICATION_API_V2 }}
        run: npm run deploy -- --network ${{ inputs.network }}

      - name: Update config.json with Diamond address
        if: inputs.network != 'hardhat'
        env:
          # Note: it is required to define both private key env variables when calling Hardhat.
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
        run: npx hardhat run scripts/tools/update-config.ts --network ${{ inputs.network }}

      - name: Push artifacts to the current branch
        if: inputs.network != 'hardhat' && github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            config/config.json
            deployments/${{ inputs.network }}/
          commit_message: ${{ env.COMMIT_MESSAGE }}
          commit_user_name: ${{ env.GHA_BOT_NAME }}
          commit_user_email: ${{ env.GHA_BOT_EMAIL }}
          commit_author: '${{ env.GHA_BOT_NAME }} <${{ env.GHA_BOT_EMAIL }}>'

      # Since the `main` branch is protected, create a PR to push artifacts.
      - name: Push artifacts through a pull request
        if: inputs.network != 'hardhat' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            config/config.json
            deployments/${{ inputs.network }}/
          commit-message: ${{ env.COMMIT_MESSAGE }}
          committer: '${{ env.GHA_BOT_NAME }} <${{ env.GHA_BOT_EMAIL }}>'
          author: '${{ env.GHA_BOT_NAME }} <${{ env.GHA_BOT_EMAIL }}>'
          branch: chore/save-artifacts-${{ inputs.network }}
          title: ${{ env.COMMIT_MESSAGE }}
          draft: true
          body: |
            ðŸ¤– This is an automated pull request to save deployment artifacts.
            * Network: `${{ inputs.network }}`
            * Job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            **Note**: Verify deployment before merging this PR.
